            'decode_mA1': (decode_in_mem, (rle._decode_mA, rle_A1), raw_1),
            'decode_mA2': (decode_in_mem, (rle._decode_mA, rle_A2), raw_2),
            'encode_mB1': (encode_in_mem, (rle._encode_mB, raw_1), rle_B1),
            'encode_mB2': (encode_in_mem, (rle._encode_mB, raw_2), rle_B2),
            'decode_mB1': (decode_in_mem, (rle._decode_mB, rle_B1), raw_1),
            'decode_mB2': (decode_in_mem, (rle._decode_mB, rle_B2), raw_2),
            'encode_file_C1': (encode_file_and_read, (rle.RLEMethod.A, 'dadosX.bin'), rle_C1),
            'encode_file_C2': (encode_file_and_read, (rle.RLEMethod.B, 'dadosX.bin'), rle_C2),
            'encode_file_D1': (encode_file_and_read, (rle.RLEMethod.A, 'dadosY.bin'), rle_D1),
            'encode_file_D2': (encode_file_and_read, (rle.RLEMethod.B, 'dadosY.bin'), rle_D2),
            'encode_file_E1': (encode_file_and_read, (rle.RLEMethod.A, 'dadosZ.bin'), rle_E1),
            'encode_file_E2': (encode_file_and_read, (rle.RLEMethod.B, 'dadosZ.bin'), rle_E2),

            'teste_pateta'   : (sum,           ((1, 2, 3),             ),  7   ),